name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        configuration: ['Release', 'Debug']
        architecture: ['Win32', 'x64']

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set repo variable
      run: |
        $repo = "${{ github.repository }}".Split("/")[1]
        echo "REPO=$repo" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Build
      run: msbuild /m '/p:Platform=${{ matrix.architecture }};Configuration=${{ matrix.configuration }}' src\${{ env.REPO }}.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPO }}-${{ matrix.architecture }}-${{ matrix.configuration }}
        path: component/${{ matrix.architecture }}/

  release:
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/')
      needs:
        - build

      steps:
      - name: Set repo and version variable
        run: |
          echo "REPO=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v1
        with:
          name: ${{ env.REPO }}-Win32-Release
          path: artifacts/${{ env.REPO }}-Win32/

      - uses: actions/download-artifact@v1
        with:
          name: ${{ env.REPO }}-x64-Release
          path: artifacts/${{ env.REPO }}-x64/

      - name: Generate fb2k component packages
        run: |
          mkdir artifacts/release/
          cd artifacts/${{ env.REPO }}-Win32/
          zip ../release/${{ env.REPO }}-$VERSION.fb2k-component *
          cd ../artifacts/${{ env.REPO }}-x64/
          zip ../release/${{ env.REPO }}-x64-$VERSION.fb2k-component *

      - name: Generate checksums
        run: |
          cd artifacts/release/
          sha256sum * > SHA256SUMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
